version: '3'
services:
  apache:
    image: php:7.0-apache
    container_name: apache
    volumes:
      - ./htdocs:/var/www/html
      - ./conf/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./logs/apache:/var/www/logs/apache
    ports:
      - "80:80"
    depends_on:
      - mysql
      - phpmyadmin
    links:
      - mysql

  mysql:
    image: mysql:latest
    container_name: db
    volumes:
      - ./mysql_data:/var/lib/mysql
        #      - ./conf/my.cnf:/etc/mysql/my.cnf
        #- ./conf:/etc/mysql
      - ./logs/mysql:/var/www/logs/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor

  php:
    image: php:7.0-apache
    container_name: php
    volumes:
      - ./htdocs:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      - ./logs/php:/var/www/logs/php
    depends_on:
      - mysql
    links:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: admin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql

